### ISSUE TITLE
This can be written easier.

### ISSUE THREAD

**Issue by iwangu** [nickolaos77/HN_filter#1]
https://github.com/nickolaos77/HN_filter/blob/ee2e6f8dd233b096b2f1d19fb11cd40c36993eda/app.js#L46

Please use includes instead of indexOf:
https://stackoverflow.com/questions/35370222/array-prototype-includes-vs-array-prototype-indexof

**Comment by iwangu** [comment]
"return true" is implied and can be ommitted

**Comment by nickolaos77** [comment]
We did it!
